/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as EmpezarRouteImport } from './routes/empezar'
import { Route as MiRegistroRouteImport } from './routes/mi-registro'
import { Route as AdministracionIndexRouteImport } from './routes/administracion.index'
import { Route as AdministracionConvocatoriasRouteImport } from './routes/administracion.convocatorias'
import { Route as AdministracionEquipoRouteImport } from './routes/administracion.equipo'
import { Route as AdministracionRegistrosRouteImport } from './routes/administracion.registros'
import { Route as AutorizarTokenRouteImport } from './routes/autorizar.$token'
import { Route as CrearCuentaIndexRouteImport } from './routes/crear-cuenta.index'
import { Route as CrearCuentaSplatRouteImport } from './routes/crear-cuenta.$'
import { Route as EntrarIndexRouteImport } from './routes/entrar.index'
import { Route as EntrarSplatRouteImport } from './routes/entrar.$'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as AdministracionRegistrosIdRouteImport } from './routes/administracion.registros.$id'
import { Route as InvitacionTokenSplatRouteImport } from './routes/invitacion.$token.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpezarRoute = EmpezarRouteImport.update({
  id: '/empezar',
  path: '/empezar',
  getParentRoute: () => rootRouteImport,
} as any)
const MiRegistroRoute = MiRegistroRouteImport.update({
  id: '/mi-registro',
  path: '/mi-registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionIndexRoute = AdministracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionConvocatoriasRoute =
  AdministracionConvocatoriasRouteImport.update({
    id: '/convocatorias',
    path: '/convocatorias',
    getParentRoute: () => AdministracionRoute,
  } as any)
const AdministracionEquipoRoute = AdministracionEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionRegistrosRoute = AdministracionRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AdministracionRoute,
} as any)
const AutorizarTokenRoute = AutorizarTokenRouteImport.update({
  id: '/autorizar/$token',
  path: '/autorizar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaIndexRoute = CrearCuentaIndexRouteImport.update({
  id: '/crear-cuenta/',
  path: '/crear-cuenta/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaSplatRoute = CrearCuentaSplatRouteImport.update({
  id: '/crear-cuenta/$',
  path: '/crear-cuenta/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarIndexRoute = EntrarIndexRouteImport.update({
  id: '/entrar/',
  path: '/entrar/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarSplatRoute = EntrarSplatRouteImport.update({
  id: '/entrar/$',
  path: '/entrar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRegistrosIdRoute =
  AdministracionRegistrosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdministracionRegistrosRoute,
  } as any)
const InvitacionTokenSplatRoute = InvitacionTokenSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => InvitacionTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/administracion/convocatorias': typeof AdministracionConvocatoriasRoute
  '/administracion/equipo': typeof AdministracionEquipoRoute
  '/administracion/registros': typeof AdministracionRegistrosRouteWithChildren
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/invitacion/$token': typeof InvitacionTokenRouteWithChildren
  '/administracion/': typeof AdministracionIndexRoute
  '/crear-cuenta/': typeof CrearCuentaIndexRoute
  '/entrar/': typeof EntrarIndexRoute
  '/administracion/registros/$id': typeof AdministracionRegistrosIdRoute
  '/invitacion/$token/$': typeof InvitacionTokenSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/administracion/convocatorias': typeof AdministracionConvocatoriasRoute
  '/administracion/equipo': typeof AdministracionEquipoRoute
  '/administracion/registros': typeof AdministracionRegistrosRouteWithChildren
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/invitacion/$token': typeof InvitacionTokenRouteWithChildren
  '/administracion': typeof AdministracionIndexRoute
  '/crear-cuenta': typeof CrearCuentaIndexRoute
  '/entrar': typeof EntrarIndexRoute
  '/administracion/registros/$id': typeof AdministracionRegistrosIdRoute
  '/invitacion/$token/$': typeof InvitacionTokenSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/administracion/convocatorias': typeof AdministracionConvocatoriasRoute
  '/administracion/equipo': typeof AdministracionEquipoRoute
  '/administracion/registros': typeof AdministracionRegistrosRouteWithChildren
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/invitacion/$token': typeof InvitacionTokenRouteWithChildren
  '/administracion/': typeof AdministracionIndexRoute
  '/crear-cuenta/': typeof CrearCuentaIndexRoute
  '/entrar/': typeof EntrarIndexRoute
  '/administracion/registros/$id': typeof AdministracionRegistrosIdRoute
  '/invitacion/$token/$': typeof InvitacionTokenSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/administracion/convocatorias'
    | '/administracion/equipo'
    | '/administracion/registros'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/invitacion/$token'
    | '/administracion/'
    | '/crear-cuenta/'
    | '/entrar/'
    | '/administracion/registros/$id'
    | '/invitacion/$token/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/administracion/convocatorias'
    | '/administracion/equipo'
    | '/administracion/registros'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/invitacion/$token'
    | '/administracion'
    | '/crear-cuenta'
    | '/entrar'
    | '/administracion/registros/$id'
    | '/invitacion/$token/$'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/administracion/convocatorias'
    | '/administracion/equipo'
    | '/administracion/registros'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/invitacion/$token'
    | '/administracion/'
    | '/crear-cuenta/'
    | '/entrar/'
    | '/administracion/registros/$id'
    | '/invitacion/$token/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRoute: typeof AdministracionRouteWithChildren
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  BasesRoute: typeof BasesRoute
  EmpezarRoute: typeof EmpezarRoute
  MiRegistroRoute: typeof MiRegistroRoute
  AutorizarTokenRoute: typeof AutorizarTokenRoute
  CrearCuentaSplatRoute: typeof CrearCuentaSplatRoute
  EntrarSplatRoute: typeof EntrarSplatRoute
  InvitacionTokenRoute: typeof InvitacionTokenRouteWithChildren
  CrearCuentaIndexRoute: typeof CrearCuentaIndexRoute
  EntrarIndexRoute: typeof EntrarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empezar': {
      id: '/empezar'
      path: '/empezar'
      fullPath: '/empezar'
      preLoaderRoute: typeof EmpezarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-registro': {
      id: '/mi-registro'
      path: '/mi-registro'
      fullPath: '/mi-registro'
      preLoaderRoute: typeof MiRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/convocatorias': {
      id: '/administracion/convocatorias'
      path: '/convocatorias'
      fullPath: '/administracion/convocatorias'
      preLoaderRoute: typeof AdministracionConvocatoriasRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/equipo': {
      id: '/administracion/equipo'
      path: '/equipo'
      fullPath: '/administracion/equipo'
      preLoaderRoute: typeof AdministracionEquipoRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/registros': {
      id: '/administracion/registros'
      path: '/registros'
      fullPath: '/administracion/registros'
      preLoaderRoute: typeof AdministracionRegistrosRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/autorizar/$token': {
      id: '/autorizar/$token'
      path: '/autorizar/$token'
      fullPath: '/autorizar/$token'
      preLoaderRoute: typeof AutorizarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta/': {
      id: '/crear-cuenta/'
      path: '/crear-cuenta'
      fullPath: '/crear-cuenta/'
      preLoaderRoute: typeof CrearCuentaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta/$': {
      id: '/crear-cuenta/$'
      path: '/crear-cuenta/$'
      fullPath: '/crear-cuenta/$'
      preLoaderRoute: typeof CrearCuentaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/': {
      id: '/entrar/'
      path: '/entrar'
      fullPath: '/entrar/'
      preLoaderRoute: typeof EntrarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/$': {
      id: '/entrar/$'
      path: '/entrar/$'
      fullPath: '/entrar/$'
      preLoaderRoute: typeof EntrarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/registros/$id': {
      id: '/administracion/registros/$id'
      path: '/$id'
      fullPath: '/administracion/registros/$id'
      preLoaderRoute: typeof AdministracionRegistrosIdRouteImport
      parentRoute: typeof AdministracionRegistrosRoute
    }
    '/invitacion/$token/$': {
      id: '/invitacion/$token/$'
      path: '/$'
      fullPath: '/invitacion/$token/$'
      preLoaderRoute: typeof InvitacionTokenSplatRouteImport
      parentRoute: typeof InvitacionTokenRoute
    }
  }
}

interface AdministracionRegistrosRouteChildren {
  AdministracionRegistrosIdRoute: typeof AdministracionRegistrosIdRoute
}

const AdministracionRegistrosRouteChildren: AdministracionRegistrosRouteChildren =
  {
    AdministracionRegistrosIdRoute: AdministracionRegistrosIdRoute,
  }

const AdministracionRegistrosRouteWithChildren =
  AdministracionRegistrosRoute._addFileChildren(
    AdministracionRegistrosRouteChildren,
  )

interface AdministracionRouteChildren {
  AdministracionConvocatoriasRoute: typeof AdministracionConvocatoriasRoute
  AdministracionEquipoRoute: typeof AdministracionEquipoRoute
  AdministracionRegistrosRoute: typeof AdministracionRegistrosRouteWithChildren
  AdministracionIndexRoute: typeof AdministracionIndexRoute
}

const AdministracionRouteChildren: AdministracionRouteChildren = {
  AdministracionConvocatoriasRoute: AdministracionConvocatoriasRoute,
  AdministracionEquipoRoute: AdministracionEquipoRoute,
  AdministracionRegistrosRoute: AdministracionRegistrosRouteWithChildren,
  AdministracionIndexRoute: AdministracionIndexRoute,
}

const AdministracionRouteWithChildren = AdministracionRoute._addFileChildren(
  AdministracionRouteChildren,
)

interface InvitacionTokenRouteChildren {
  InvitacionTokenSplatRoute: typeof InvitacionTokenSplatRoute
}

const InvitacionTokenRouteChildren: InvitacionTokenRouteChildren = {
  InvitacionTokenSplatRoute: InvitacionTokenSplatRoute,
}

const InvitacionTokenRouteWithChildren = InvitacionTokenRoute._addFileChildren(
  InvitacionTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRoute: AdministracionRouteWithChildren,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  BasesRoute: BasesRoute,
  EmpezarRoute: EmpezarRoute,
  MiRegistroRoute: MiRegistroRoute,
  AutorizarTokenRoute: AutorizarTokenRoute,
  CrearCuentaSplatRoute: CrearCuentaSplatRoute,
  EntrarSplatRoute: EntrarSplatRoute,
  InvitacionTokenRoute: InvitacionTokenRouteWithChildren,
  CrearCuentaIndexRoute: CrearCuentaIndexRoute,
  EntrarIndexRoute: EntrarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
