/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as EmpezarRouteImport } from './routes/empezar'
import { Route as MiRegistroRouteImport } from './routes/mi-registro'
import { Route as AutorizarTokenRouteImport } from './routes/autorizar.$token'
import { Route as CrearCuentaIndexRouteImport } from './routes/crear-cuenta.index'
import { Route as CrearCuentaSplatRouteImport } from './routes/crear-cuenta.$'
import { Route as EntrarIndexRouteImport } from './routes/entrar.index'
import { Route as EntrarSplatRouteImport } from './routes/entrar.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpezarRoute = EmpezarRouteImport.update({
  id: '/empezar',
  path: '/empezar',
  getParentRoute: () => rootRouteImport,
} as any)
const MiRegistroRoute = MiRegistroRouteImport.update({
  id: '/mi-registro',
  path: '/mi-registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizarTokenRoute = AutorizarTokenRouteImport.update({
  id: '/autorizar/$token',
  path: '/autorizar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaIndexRoute = CrearCuentaIndexRouteImport.update({
  id: '/crear-cuenta/',
  path: '/crear-cuenta/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaSplatRoute = CrearCuentaSplatRouteImport.update({
  id: '/crear-cuenta/$',
  path: '/crear-cuenta/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarIndexRoute = EntrarIndexRouteImport.update({
  id: '/entrar/',
  path: '/entrar/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarSplatRoute = EntrarSplatRouteImport.update({
  id: '/entrar/$',
  path: '/entrar/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/crear-cuenta/': typeof CrearCuentaIndexRoute
  '/entrar/': typeof EntrarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/crear-cuenta': typeof CrearCuentaIndexRoute
  '/entrar': typeof EntrarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/bases': typeof BasesRoute
  '/empezar': typeof EmpezarRoute
  '/mi-registro': typeof MiRegistroRoute
  '/autorizar/$token': typeof AutorizarTokenRoute
  '/crear-cuenta/$': typeof CrearCuentaSplatRoute
  '/entrar/$': typeof EntrarSplatRoute
  '/crear-cuenta/': typeof CrearCuentaIndexRoute
  '/entrar/': typeof EntrarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/crear-cuenta/'
    | '/entrar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/crear-cuenta'
    | '/entrar'
  id:
    | '__root__'
    | '/'
    | '/aviso-de-privacidad'
    | '/bases'
    | '/empezar'
    | '/mi-registro'
    | '/autorizar/$token'
    | '/crear-cuenta/$'
    | '/entrar/$'
    | '/crear-cuenta/'
    | '/entrar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  BasesRoute: typeof BasesRoute
  EmpezarRoute: typeof EmpezarRoute
  MiRegistroRoute: typeof MiRegistroRoute
  AutorizarTokenRoute: typeof AutorizarTokenRoute
  CrearCuentaSplatRoute: typeof CrearCuentaSplatRoute
  EntrarSplatRoute: typeof EntrarSplatRoute
  CrearCuentaIndexRoute: typeof CrearCuentaIndexRoute
  EntrarIndexRoute: typeof EntrarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empezar': {
      id: '/empezar'
      path: '/empezar'
      fullPath: '/empezar'
      preLoaderRoute: typeof EmpezarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-registro': {
      id: '/mi-registro'
      path: '/mi-registro'
      fullPath: '/mi-registro'
      preLoaderRoute: typeof MiRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizar/$token': {
      id: '/autorizar/$token'
      path: '/autorizar/$token'
      fullPath: '/autorizar/$token'
      preLoaderRoute: typeof AutorizarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta/': {
      id: '/crear-cuenta/'
      path: '/crear-cuenta'
      fullPath: '/crear-cuenta/'
      preLoaderRoute: typeof CrearCuentaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta/$': {
      id: '/crear-cuenta/$'
      path: '/crear-cuenta/$'
      fullPath: '/crear-cuenta/$'
      preLoaderRoute: typeof CrearCuentaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/': {
      id: '/entrar/'
      path: '/entrar'
      fullPath: '/entrar/'
      preLoaderRoute: typeof EntrarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/$': {
      id: '/entrar/$'
      path: '/entrar/$'
      fullPath: '/entrar/$'
      preLoaderRoute: typeof EntrarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  BasesRoute: BasesRoute,
  EmpezarRoute: EmpezarRoute,
  MiRegistroRoute: MiRegistroRoute,
  AutorizarTokenRoute: AutorizarTokenRoute,
  CrearCuentaSplatRoute: CrearCuentaSplatRoute,
  EntrarSplatRoute: EntrarSplatRoute,
  CrearCuentaIndexRoute: CrearCuentaIndexRoute,
  EntrarIndexRoute: EntrarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
